name: pymepps
channels: !!python/tuple
  - conda-forge
  - defaults
dependencies:
  - conda-forge::matplotlib
  - conda-forge::pygrib
  - conda-forge::numpy
  - conda-forge::pandas
  - conda-forge::python=3.5
  - conda-forge::scipy
  - conda-forge::xarray
- pip:
  - netcdf4
  - cdo
