name: pymepps-rtd
channels: !!python/tuple
  - conda-forge
  - defaults
dependencies:
  - conda-forge::basemap
  - conda-forge::ipython
  - conda-forge::matplotlib
  - conda-forge::numpy
  - conda-forge::openblas
  - conda-forge::pygrib
  - conda-forge::pandas
  - conda-forge::python=3.5
  - conda-forge::scipy
  - conda-forge::tqdm
  - conda-forge::xarray
  - conda-forge::pip
  - conda-forge::pycairo
  - pip:
    - netcdf4
    - cdo
#    - git+https://github.com/maestrotf/pymepps.git